language: php
sudo: false

env:
  global:
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit

matrix:
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: nightly

before_install:
    - composer self-update
    - composer clear-cache

install:
    - travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable

script:
    - yarn
    - yarn run build
    - ./vendor/bin/phpunit
